### ISSUE TITLE
v6 tag not the latest v6

### ISSUE THREAD

**Issue by taspeotis** [rsms/raster#8]
Thanks for the library. I found that while browsing the repository that the v6 tag is https://github.com/rsms/raster/commit/493c5f0ca49daf4c4b5544aafa6e79d1e645f780 but it's the commit after (https://github.com/rsms/raster/commit/5dca1b94d5f80ecdb5e92975cfbbca5f9ecba8bf) that actually puts v6 into `raster.css` etc.

**Comment by rsms** [comment]
Yup. But YOLO.
